Controllers/AdminController.cs
using S_me.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Data;
using System.Data.Entity;
using System.Net;
using System.Text;
using System.Web.Security;
namespace S_me.Controllers
{
    public class AdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult AdminLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AdminLogin(Admin model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            ApplicationDbContext db = new ApplicationDbContext();
            var dataItem = db.Admins.Where(x => x.UserAdmin == model.UserAdmin && x.PassAdmin == model.PassAdmin).SingleOrDefault();
            if (dataItem != null)
            {
                FormsAuthentication.SetAuthCookie(dataItem.UserAdmin, false);
                if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                    && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ModelState.AddModelError("", "Đăng nhập không thành công. Vui lòng kiểm tra lại thông tin đăng nhập.");
                return View(model);
            }
        }

        // Thuộc Sản phẩm
        public ActionResult QLSanpham()
        {
            return View(db.Sanphams.ToList());
        }
        // GET: Sanphams/Details/5
        public ActionResult Chitietsanpham(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sanpham sanpham = db.Sanphams.Find(id);
            if (sanpham == null)
            {
                return HttpNotFound();
            }
            return View(sanpham);
        }

        // GET: Sanphams/Create
        public ActionResult SpThem()
        {
            ViewBag.CatID = new SelectList(db.Danhmucs, "DMID", "Name");
            ViewBag.BrandID = new SelectList(db.Thuonghieux, "ThuonghieuID", "Name");
            return View();
        }

        // POST: Sanphams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SpThem([Bind(Include = "SpID,ProductName,Price,Summary,Rated,Storage,CatID,BrandID")] Sanpham sanpham)
        {
            if (ModelState.IsValid)
            {
                sanpham.Picture = new byte[sanpham.PictureUpload.ContentLength];
                sanpham.PictureUpload.InputStream.Read(sanpham.Picture, 0, sanpham.PictureUpload.ContentLength);

                sanpham.Picture2 = new byte[sanpham.PictureUpload2.ContentLength];
                sanpham.PictureUpload2.InputStream.Read(sanpham.Picture2, 0, sanpham.PictureUpload2.ContentLength);

                db.Sanphams.Add(sanpham);
                db.SaveChanges();
                return RedirectToAction("QLSanpham");
            }

            ViewBag.CatID = new SelectList(db.Danhmucs, "DMID", "Name", sanpham.CatID);
            ViewBag.BrandID = new SelectList(db.Thuonghieux, "ThuonghieuID", "Name", sanpham.BrandID);
            return View(sanpham);
        }

        // GET: Sanphams/Edit/5
        public ActionResult SpSua(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sanpham sanpham = db.Sanphams.Find(id);
            if (sanpham == null)
            {
                return HttpNotFound();
            }
            ViewBag.CatID = new SelectList(db.Danhmucs, "DMID", "Name", sanpham.CatID);
            ViewBag.BrandID = new SelectList(db.Thuonghieux, "ThuonghieuID", "Name", sanpham.BrandID);
            return View(sanpham);
        }

        // POST: Sanphams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SpSua([Bind(Include = "SpID,ProductName,Price,Summary,Picture,Picture2,Rated,Storage,CatID,BrandID")] Sanpham sanpham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanpham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("QLSanpham");
            }
            ViewBag.CatID = new SelectList(db.Danhmucs, "DMID", "Name", sanpham.CatID);
            ViewBag.BrandID = new SelectList(db.Thuonghieux, "ThuonghieuID", "Name", sanpham.BrandID);
            return View(sanpham);
        }

        // GET: Sanphams/Delete/5
        public ActionResult SpXoa(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sanpham sanpham = db.Sanphams.Find(id);
            if (sanpham == null)
            {
                return HttpNotFound();
            }
            return View(sanpham);
        }

        // POST: Sanphams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sanpham sanpham = db.Sanphams.Find(id);
            db.Sanphams.Remove(sanpham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Kết thúc sản phẩm



        // Thuộc Thương hiệu
        public ActionResult QLThuonghieu()
        {
            return View(db.Thuonghieux.ToList());
        }
        // GET: Thuonghieux/Details/5
        public ActionResult THChitiet(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thuonghieu thuonghieu = db.Thuonghieux.Find(id);
            if (thuonghieu == null)
            {
                return HttpNotFound();
            }
            return View(thuonghieu);
        }

        // GET: Thuonghieux/Create
        public ActionResult THThem()
        {
            return View();
        }

        // POST: Thuonghieux/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult THThem([Bind(Include = "ThuonghieuID,Name")] Thuonghieu thuonghieu)
        {
            if (ModelState.IsValid)
            {
                db.Thuonghieux.Add(thuonghieu);
                db.SaveChanges();
                return RedirectToAction("QLThuonghieu");
            }

            return View(thuonghieu);
        }

        // GET: Thuonghieux/Edit/5
        public ActionResult THSua(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thuonghieu thuonghieu = db.Thuonghieux.Find(id);
            if (thuonghieu == null)
            {
                return HttpNotFound();
            }
            return View(thuonghieu);
        }

        // POST: Thuonghieux/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult THSua([Bind(Include = "ThuonghieuID,Name")] Thuonghieu thuonghieu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(thuonghieu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("QLThuonghieu");
            }
            return View(thuonghieu);
        }

        // GET: Thuonghieux/Delete/5
        public ActionResult THXoa(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Thuonghieu thuonghieu = db.Thuonghieux.Find(id);
            if (thuonghieu == null)
            {
                return HttpNotFound();
            }
            return View(thuonghieu);
        }

        // POST: Thuonghieux/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmedTH(int id)
        {
            Thuonghieu thuonghieu = db.Thuonghieux.Find(id);
            db.Thuonghieux.Remove(thuonghieu);
            db.SaveChanges();
            return RedirectToAction("QLThuonghieu");
        }
        //Kết thúc thương hiệu



        // Thuộc Danh mục
        public ActionResult QLDanhmuc()
        {

Controllers/SanphamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using S_me.Models;

namespace S_me.Controllers
{
    public class SanphamsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Sanphams
        public ActionResult Index()
        {
            var sanphams = db.Sanphams.Include(s => s.DanhmucObj).Include(s => s.ThuonghieuObj);
            return View(sanphams.ToList());
        }

        // Lấy chi tiết sản phẩm và hiển thị qua Viewmodel
        public ActionResult Chitietsanpham(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Sanpham sanpham = db.Sanphams.Find(id);

            if (sanpham == null)
            {
                return HttpNotFound();
            }

            // Lấy danh sách sản phẩm liên quan
            var sanphamLienQuans = db.Sanphams.Where(s => s.DanhmucObj.DMID == sanpham.DanhmucObj.DMID && s.SpID != id).ToList();

            // Tạo ViewModel
            var viewModel = new ChitietsanphamViewModel
            {
                Sanphamchinh = sanpham,
                Sanphamlienquans = sanphamLienQuans
            };

            // Trả về view với ViewModel
            return View(viewModel);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Themvaogiohang(int id)
        {
            //Kiem tra Id sanpham ton tai hay khong
            var sanpham = db.Sanphams.Where(x => x.SpID == id).FirstOrDefault();
            if (sanpham == null)
            {
                return RedirectToAction("Index");
            }
            var Hoadon = this.Session["Donhang"] as Donhang;
            if (Hoadon == null)
            {
                Hoadon = new Donhang();
                Hoadon.NgayLap = DateTime.Now;
                Hoadon.Chitietdonhangs = new List<Chitietdonhang>();
                this.Session["Donhang"] = Hoadon;
                Hoadon.KHID = 1;
                db.Donhangs.Add(Hoadon);
            }

            //Kiem tra don hang da co truoc do
            var Chitiethoadon = Hoadon.Chitietdonhangs.Where(x => x.SanphamObj.SpID ==id).FirstOrDefault();
            if (Chitiethoadon == null)
            {
                Chitiethoadon = new Chitietdonhang();
                Chitiethoadon.SpID = id;
                Chitiethoadon.SanphamObj = sanpham;
                Chitiethoadon.DHObj = Hoadon;
                Chitiethoadon.Soluong = 1;
                Hoadon.Chitietdonhangs.Add(Chitiethoadon);
            }
            else
            {
                Chitiethoadon.Soluong++;
            }
            db.SaveChanges();
            return View(Hoadon);
        }

        public ActionResult Xoakhoigiohang(int SpIDs)
        {
            var Hoadon = this.Session["Donhang"] as Donhang;
            var Chitiethoadon = Hoadon.Chitietdonhangs.Where(x => x.SanphamObj.SpID ==
            SpIDs).FirstOrDefault();
            Hoadon.Chitietdonhangs.Remove(Chitiethoadon);
            return View("Themvaogiohang", Hoadon);
        }

        public PartialViewResult Summary()
        {
            var Hoadon = this.Session["Donhang"] as Donhang;
            if (Hoadon == null)
            {
                return null;
            }
            return PartialView(Hoadon);
        }
        public ActionResult Thanhtoan()
        {
            return View(new Thanhtoan());
        }
        [HttpPost]
        public ActionResult Thanhtoan(Thanhtoan detail)
        {
            var Hoadon = this.Session["Donhang"] as Donhang;
            if (Hoadon.Chitietdonhangs.Count() == 0)
            {
                ModelState.AddModelError("", "Ôi không! Bạn chưa bỏ gì vào giỏ hàng mà!");
            }
            if (ModelState.IsValid)
            {
                StringBuilder body = new StringBuilder()
                .AppendLine("A new order has been submitted")
                .AppendLine("---")
                .AppendLine("Items:");
                foreach (var Chitiethoadon in Hoadon.Chitietdonhangs)
                {
                    var subtotal = Chitiethoadon.SanphamObj.Price * Chitiethoadon.Soluong;
                    body.AppendFormat("{0} x {1} (subtotal: {2:c}", Chitiethoadon.Soluong,
                    Chitiethoadon.SanphamObj.ProductName,
                    subtotal);
                }
                body.AppendFormat("Total order value: {0:c}", Hoadon.TongTien)
                .AppendLine("---")
                .AppendLine("Ship to:")
                .AppendLine(detail.Name)
                .AppendLine(detail.Address)
                .AppendLine(detail.Mobile.ToString());
                Email.SendEmail(new IdentityMessage()
                {
                    Destination = detail.Email,
                    Subject = "Đơn hàng thành công!",
                    Body = body.ToString()
                });
                this.Session["Donhang"] = null;
                return View("Thanhtoanthanhcong");
            }
            else
            {
                return View(new Thanhtoan());
            }
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -  S-me Shop</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <!-- google font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,900&display=swap" rel="stylesheet">
    <!-- boxicons -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <!-- css -->
    <link href="~/Content/css/index.css" rel="stylesheet" />
    <link href="~/Content/css/grid.css" rel="stylesheet" />
</head>
<body>


    <!-- header -->
    <nav>
        <header style=" top:0px;width:100%; z-index:100;">
            <!-- mobile menu -->
            <div class="mobile-menu bg-second">
                @Html.ActionLink("S-me", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                <span class="mb-menu-toggle" id="mb-menu-toggle">
                    <i class='bx bx-menu'></i>
                </span>
            </div>
            <!-- end mobile menu -->
            <!-- main header -->
            <div class="header-wrapper" id="header-wrapper">
                <span class="mb-menu-toggle mb-menu-close" id="mb-menu-close">
                    <i class='bx bx-x'></i>
                </span>
                <!-- top header -->
                <div class="bg-main mid-header container">
                    <div class="logo">
                        @Html.ActionLink("S-me", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                    </div>
                    <div class="search">
                        <input type="text" placeholder="Tìm kiếm">
                        <i class='bx bx-search-alt'></i>
                    </div>
                    <div class="logo">
                        @Html.ActionLink("ADMIN HOME", "Index", "Admin", new { area = "" }, new { @class = "nav-link" })
                    </div>
                </div>
                <!-- end top header -->
                <!-- bottom header -->
                <div class="bg-second">
                    <div class="bottom-header container">
                        <ul class="main-menu">
                            <li>@Html.ActionLink("Trang chủ", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                            <!-- mega menu -->
                            <li class="mega-dropdown">
                                @*<a href="./products.html">Cửa Hàng<i class='bx bxs-chevron-down'></i></a>*@
                                @Html.ActionLink("Quản lý", "Index", "Sanphams", new { area = "" }, new { @class = "nav-link" })
                                <div class="mega-content">
                                    <div class="row">
                                        <div class="col-3 col-md-12">
                                            <div class="box">
                                                <ul>
                                                    <li>
                                                        @Html.ActionLink("Quản lý Sản phẩm", "QLSanpham", "Admin", new { area = "" }, new { @class = "nav-link" })
                                                    </li>
                                                    <li>
                                                        @Html.ActionLink("Quản lý Thương hiệu", "QLThuonghieu", "Admin", new { area = "" }, new { @class = "nav-link" })
                                                    </li>
                                                    <li>
                                                        @Html.ActionLink("Quản lý Danh mục", "QLDanhmuc", "Admin", new { area = "" }, new { @class = "nav-link" })
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </li>
                            <!-- end mega menu -->
                            <li>@Html.ActionLink("Phản hồi", "ViewForm", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                            @*<li>@Html.ActionLink("Liên hệ", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                                <li>@Html.ActionLink("Tài khoản", "Login", "Account", new { area = "" }, new { @class = "nav-link" })</li>*@
                        </ul>
                    </div>
                </div>
                <!-- end bottom header -->
            </div>
            <!-- end main header -->
        </header>
        <!-- end header -->
    </nav>
    <br><br>

    @RenderBody()
    <!-- footer -->
    <br><br>
    <footer class="bg-second">
        <div class="container">
            <div class="row">
                <div class="col-3 col-md-6">
                    <h3 class="footer-head">Danh mục sản phẩm</h3>
                    <ul class="menu">
                        <li><a href="#">Bóng rổ</a></li>
                        <li><a href="#">Bóng chuyền</a></li>
                        <li><a href="#">Bơi lội</a></li>
                        <li><a href="#">Cầu lông</a></li>
                        <li><a href="#">Gym</a></li>
                    </ul>
                </div>
                <div class="col-3 col-md-6">
                    <h3 class="footer-head">Trang</h3>
                    <ul class="menu">
                        <li>@Html.ActionLink("S-me", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Cửa hàng", "Index", "Sanphams", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Về chúng tôi", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Liên hệ", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Tài khoản", "Login", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
                <div class="col-3 col-md-6">
                    <h3 class="footer-head">Hỗ trợ</h3>
                    <ul class="menu">
                        <li><a href="#">Tổng đài</a></li>
                        <li><a href="#">Thông tin liên hệ</a></li>
                        <li><a href="#">Hỏi đáp sản phẩm</a></li>
                        <li><a href="#">Bảo hành</a></li>
                        <li><a href="#">Theo dõi đơn hàng</a></li>
                    </ul>
                </div>
                <div class="col-3 col-md-6 col-sm-12">
                    <div class="contact">
                        <h3 class="contact-header">
                            @Html.ActionLink("S-me", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </h3>
                        <ul class="contact-socials">
                            <li>
                                <a href="#">
                                    <i class='bx bxl-facebook-circle'></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class='bx bxl-instagram-alt'></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class='bx bxl-youtube'></i>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class='bx bxl-twitter'></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="subscribe">
                        <input type="email" placeholder="Nhập email của bạn">
                        <button>Nhận thông tin</button>
                    </div>
                </div>
            </div>
            <br>
            <center><p>&copy; @DateTime.Now.Year - Powered by S-me Shop</p></center>
        </div>
    </footer>
    <!-- end footer -->
    @*<hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>*@



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/js/index.js"></script>
    <script src="~/Scripts/js/app.js"></script>
</body>
</html>